### ISSUE TITLE
OOM了老哥，求助

### ISSUE THREAD

**Issue by aa563011992** [licheedev/Modbus4Android#14]
java.lang.OutOfMemoryError: pthread_create (stack size 16384 bytes) failed: Try again
	at java.lang.VMThread.create(Native Method)
	at java.lang.Thread.start(Thread.java:1029)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:920)
	at java.util.concurrent.ThreadPoolExecutor.ensurePrestart(ThreadPoolExecutor.java:1553)
	at java.util.concurrent.ScheduledThreadPoolExecutor.delayedExecute(ScheduledThreadPoolExecutor.java:306)
	at java.util.concurrent.ScheduledThreadPoolExecutor.schedule(ScheduledThreadPoolExecutor.java:519)
	at java.util.concurrent.ScheduledThreadPoolExecutor.submit(ScheduledThreadPoolExecutor.java:618)
	at io.reactivex.internal.schedulers.NewThreadWorker.scheduleActual(NewThreadWorker.java:145)
	at io.reactivex.internal.schedulers.IoScheduler$EventLoopWorker.schedule(IoScheduler.java:239)
	at io.reactivex.Scheduler.scheduleDirect(Scheduler.java:203)
	at io.reactivex.Scheduler.scheduleDirect(Scheduler.java:179)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn.subscribeActual(ObservableSubscribeOn.java:36)
	at io.reactivex.Observable.subscribe(Observable.java:12268)
	at io.reactivex.internal.operators.observable.ObservableObserveOn.subscribeActual(ObservableObserveOn.java:45)
	at io.reactivex.Observable.subscribe(Observable.java:12268)
	at io.reactivex.internal.operators.observable.ObservableDoFinally.subscribeActual(ObservableDoFinally.java:43)
	at io.reactivex.Observable.subscribe(Observable.java:12268)
	at com.licheedev.modbus4android.ModbusWorker.subscribe(ModbusWorker.java:248)
	at com.licheedev.modbus4android.ModbusWorker.readHoldingRegisters(ModbusWorker.java:604)
	at com.zgkx.change.serialport.ElectricityMeterManager.startGetEMInfo(ElectricityMeterManager.kt:109)
	at com.zgkx.change.serialport.ElectricityMeterManager$startGetEMInfo$11.run(ElectricityMeterManager.kt:226)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at com.zgkx.change.util.FreeThread$1.run(FreeThread.kt:25)
	at android.os.Handler.handleCallback(Handler.java:733)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:136)
	at android.os.HandlerThread.run(HandlerThread.java:61)
以下是代码
`            SerialPortManager.readHoldingRegisters(SerialPortManager.slaveId, Integer.parseInt("2006", 16), 2,
                    object : ModbusCallback<ReadHoldingRegistersResponse> {
                        override fun onSuccess(readHoldingRegistersResponse: ReadHoldingRegistersResponse) {
                            val data = readHoldingRegistersResponse.data
                            Ua = HexUtils.byteArrayToFloat(data) / 10f
                            DevBean.INV = Ua.toString()
                            XLogUtil.log(TAG, "Ua-onSuccess:u=${Ua},data=${HexUtils.bytesToHexString(data)}")
                        }

                        override fun onFailure(tr: Throwable) {
                            XLogUtil.log(TAG, "Ua-onFailure\n$tr")
                            tr.printStackTrace()
                        }

                        override fun onFinally() {
                            XLogUtil.log(TAG, "Ua-onFinally")
                        }
                    })`

**Comment by srdgame** [comment]
怎么解决的？ @aa563011992
